article/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'article'

urlpatterns = [
    # 文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # # 安全删除文章
    # path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # # 点赞 +1
    # path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
    #
    # # 列表类视图
    # path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    # # 详情类视图
    # path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    # # 创建类视图
    # path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    # home
    path('', article_list, name='home'),

    # 外地轮子
    path('password-reset/', include('password_reset.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.TOOL_FLAG:
    urlpatterns.append(
        path('tool/', include(('tool.urls', 'tool'), namespace='tool')))  # tool

tool/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import (Toolview, BD_pushview, BD_pushview_site,
                    regexview, useragent_view, html_characters,
                    docker_search_view, editor_view, word_cloud
                    )

urlpatterns = [
    path('', Toolview, name='total'),  # 工具汇总页
    path('baidu-linksubmit/', BD_pushview, name='baidu_push'),  # 百度主动推送
    path('baidu-linksubmit-sitemap/', BD_pushview_site, name='baidu_push_site'),  # 百度主动推送sitemap
    path('regex/', regexview, name='regex'),  # 正则表达式在线
    path('user-agent/', useragent_view, name='useragent'),  # user-agent生成器
    path('html-special-characters/', html_characters, name='html_characters'),  # HTML特殊字符查询
    path('docker-search/', docker_search_view, name='docker_search'),  #docker镜像查询
    path('markdown-editor/', editor_view, name='markdown_editor'), # editor.md 工具
    path('word-cloud/', word_cloud, name='word_cloud'), # 词云图 工具
]

userprofile/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'userprofile'
urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>

    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">
</head>

<body>

<!-- 引入导航栏 -->
{% include 'header.html' %}


<!-- 预留具体页面的位置 -->
<div id="wrapper">
    {% block content %}

    {% endblock content %}
    <div id="push"></div>
</div>


<!-- 引入注脚 -->
{% include 'footer.html' %}


<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jQuery/jQuery-3.6.1.min.js' %}"></script>

<!-- 2020.07.22: popper.js 更新为远程调用的形式 -->
<script src="{% static 'popper/popper-1.14.4.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>

{% include 'back_to_top_func.html' %}

{% block script %}

{% endblock script %}


<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -40px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>


</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="py-3" id="footer">
    <div class="container">
        <div class='m-0 text-center'>
        </div>
        <h5 class="m-0 text-center">Copyright &copy 2017-2022 Yyj2310</h5>

    </div>

</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}


<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="">
            Vigen</a>
        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">Create</a>
                </li>

                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                           role="button" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            <!-- 新增代码，小红点 -->
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}

                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!-- 新增代码，通知计数 -->
                            <a class="dropdown-item" href="#">通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="#"
                               onclick="user_delete()">delete_user</a>
                            <a class="dropdown-item"
                               href='{% url "userprofile:logout" %}'>Logout</a>
                            <a class="dropdown-item"
                               href='{% url "userprofile:edit" user.id %}'>Profile</a>

                        </div>
                    </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login">Login</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}

                <!-- 搜索栏 -->
                <div class="row">
                    <div class="col-auto mr-auto">
                        <form class="form-inline">
                            <label class="sr-only">content</label>
                            <input type="text"
                                   class="form-control mb-2 mr-sm-2"
                                   name="search"
                                   placeholder="Search..."
                                   required>
                        </form>
                    </div>
                </div>
            </ul>
        </div>
    </div>
</nav>



{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "Are u sure?",
                content: "delete your account",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}